export default {
  GET_CHAIN_STATS: "STATS",
  STATE_MINER_POWER: "STATE_MINER_POWER",
  STATE_LIST_MINERS: "STATE_LIST_MINERS",
  GET_CHAIN_HEAD: "GET_CHAIN_HEAD",
  GET_MINER_ADDRESS: "GET_MINER_ADDRESS",
  GET_WALLET_DETAILS: "GET_WALLET_DETAILS",
};
